set use_wm 1
set gui_name "nitpicker"
set report_config "yes"

if {$use_wm} {
	set gui_name "wm"
}

create_boot_directory

proc depot_user {} { return [get_cmd_arg --depot-user genodelabs] }

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/themed_wm \
                  [depot_user]/pkg/fonts_fs \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/zlib \
                  [depot_user]/src/vfs

set config {
<config prio_levels="2">
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="TRACE"/>
	</parent-provides>

	<default caps="100"/>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1500" managing_system="yes">
		<resource name="RAM" quantum="64M"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Capture"> <child name="nitpicker"/> </service>
			<service name="Event">   <child name="nitpicker"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides>
			<service name="Gui"/>
			<service name="Capture"/>
			<service name="Event"/>
		</provides>
		<config>
			<capture/>
			<event/>
			<background color="#123456"/>
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="3" content="client" label="no" hover="always" focus="click" />

			<policy label_prefix="pointer" domain="pointer"/>
			<default-policy domain="default"/>
		</config>
	</start>

	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
		<route>
			<service name="Gui"> <child name="nitpicker" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>}

append_if [expr $use_wm] config {
	<start name="wm" caps="1000">
		<resource name="RAM" quantum="32M"/>
		<binary name="init"/>
		<provides> <service name="Gui"/> <service name="Report"/> </provides>
		<route>
			<service name="ROM" label="config"> <parent label="wm.config"/> </service>
			<service name="Gui"> <child name="nitpicker"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>}

append_if [expr $report_config eq "yes"] config {
	<start name="report_rom_config">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes">
		</config>
	</start>}

append config {
	<start name="report_rom_hover">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="no">
			<policy label="top_view -> hover" report="menu_view -> hover"/>
		</config>
	</start>

	<start name="report_rom_dialog">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="no">
			<policy label="menu_view -> dialog" report="top_view -> dialog"/>
		</config>
	</start>

	<start name="report_rom_graph">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="no">
			<policy label="graph -> graph" report="top_view -> graph"/>
		</config>
	</start>

	<start name="fonts_fs" caps="300">
		<resource name="RAM" quantum="8M"/>
		<binary name="vfs"/>
		<route>
			<service name="ROM" label="config"> <parent label="fonts_fs.config"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides> <service name="File_system"/> </provides>
	</start>

	<start name="ram_fs">
		<binary name="vfs"/>
		<resource name="RAM" quantum="32M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<vfs> <ram/> </vfs>
			<policy label="top_view -> store" root="/" writeable="yes" />
			<policy label="graph -> load"     root="/" writeable="no" />
		</config>
	</start>

	<start name="menu_view" caps="200" priority="-1">
		<binary name="menu_view_ab"/>
		<resource name="RAM" quantum="16M"/>
		<config xpos="200" ypos="100">
			<report hover="yes"/>
			<libc stderr="/dev/log"/>
			<vfs>
				<tar name="menu_view_styles.tar" />
				<dir name="dev"> <log/> </dir>
				<dir name="fonts"> <fs label="fonts"/> </dir>
			</vfs>
		</config>
		<route>
			<service name="ROM" label="dialog"> <child name="report_rom_dialog" /> </service>
			<service name="Report" label="hover"> <child name="report_rom_hover"/> </service>
			<service name="File_system" label="fonts"> <child name="fonts_fs"/> </service>
			<service name="Gui"> <child name="} $gui_name {"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="top_view" priority="-1">
		<resource name="RAM" quantum="2M"/>
		<config view_ms="9000" trace_ms="3000" report="yes" log="no"
		        store="yes" report_config="} $report_config {"
		        view="list" list="components">

			<cpu xpos="0" ypos="0" show="true" threads="3"/>
			<cpu xpos="1" ypos="0" show="true" threads="4"/>
			<cpu xpos="2" ypos="0" show="false" threads="5"/>
			<cpu xpos="3" ypos="0" show="true" threads="6"/>
		</config>

		<route>
			<service name="ROM" label="hover"> <child name="report_rom_hover" /> </service>
			<service name="Report" label="dialog"> <child name="report_rom_dialog" /> </service>
			<service name="Report" label="graph"> <child name="report_rom_graph" /> </service>
			<service name="Report" label="config"> <child name="report_rom_config" /> </service>
			<service name="File_system" label="store"> <child name="ram_fs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="graph" priority="-1">
		<resource name="RAM" quantum="6M"/>
		<config store="yes" verbose="no" freq_khz="2000000">
			<vfs> <dir name="fonts"> <fs label="fonts"/> </dir> </vfs>
		</config>
		<route>
			<service name="ROM" label="graph"> <child name="report_rom_graph" /> </service>
			<service name="File_system" label="fonts"> <child name="fonts_fs"/> </service>
			<service name="File_system" label="load">  <child name="ram_fs"/> </service>
			<service name="Gui"> <child name="} $gui_name {"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

</config>}

install_config $config

build { app/menu_view_ab app/top_view app/graph }

build_boot_image { menu_view_ab menu_view_styles.tar top_view graph }

append qemu_args " -smp 4,cores=4"
run_genode_until forever
