create_boot_directory

#
# To use the themed decorator instead of the default one, replace
# 'pkg/motif_wm' with 'pkg/themed_wm'.
#

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/motif_wm \
                  [depot_user]/pkg/terminal \
                  [depot_user]/raw/genode_bg \
                  [depot_user]/pkg/backdrop \
                  [depot_user]/src/demo \
                  [depot_user]/src/init \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/nit_fb \
                  [depot_user]/src/posix \
                  [depot_user]/src/ncurses \
                  [depot_user]/src/vim \
                  [depot_user]/src/fs_rom \
                  [depot_user]/src/bash \
                  [depot_user]/src/coreutils \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_pipe \
                  [depot_user]/src/vfs_import \
                  [depot_user]/src/ram_fs

# write default vimrc file
set vimrc_fd [open [run_dir]/genode/vimrc w]
puts $vimrc_fd {
set noloadplugins
set hls
set nocompatible
set laststatus=2
set noswapfile
set viminfo=}
close $vimrc_fd

install_config {
<config prio_levels="2" verbose="true">
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1000">
		<resource name="RAM" quantum="32M" constrain_phys="yes"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides>
			<service name="Input"/> <service name="Framebuffer"/>
		</provides>
	</start>

	<start name="config_fs" caps="120">
		<resource name="RAM" quantum="30M"/>
		<binary name="vfs"/>
		<provides><service name="File_system"/></provides>
		<config>
			<vfs>
				<ram/>
				<import overwrite="yes">
					<rom name="decorator_init.config"/>
					<rom name="layouter.config"/>
				</import>
			</vfs>

			<policy label_prefix="config_fs_rom" root="/" writeable="no"/>
			<default-policy root="/" writeable="yes"/>
		</config>
	</start>

	<start name="config_fs_rom">
		<resource name="RAM" quantum="30M"/>
		<binary name="fs_rom"/>
		<provides> <service name="ROM"/> </provides>
		<config/>
		<route>
			<service name="File_system"> <child name="config_fs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Nitpicker"/></provides>
		<config focus="rom">
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="2" content="client" label="no" hover="always"/>

			<policy label_prefix="pointer" domain="pointer"/>
			<global-key name="KEY_F1" label="wm -> decorator"/>
			<default-policy domain="default"/>
		</config>
		<route>
			<service name="Framebuffer"><child name="drivers"/> </service>
			<service name="Input"><child name="drivers"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>

	</start>

	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
		<route>
			<service name="Nitpicker"> <child name="nitpicker"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="4M"/>
		<provides>
			<service name="Report"/>
			<service name="ROM"/>
		</provides>
		<config>
			<policy label="layouter -> window_list"       report="wm -> window_list"/>
			<policy label="layouter -> focus_request"     report="wm -> focus_request"/>
			<policy label="decorator -> pointer"          report="wm -> pointer"/>
			<policy label="layouter -> rules"             report="layouter -> rules"/>
			<policy label="decorator -> window_layout"    report="layouter -> window_layout"/>
			<policy label="wm -> resize_request"          report="layouter -> resize_request"/>
			<policy label="wm -> focus"                   report="layouter -> focus"/>
			<policy label="layouter -> hover"             report="decorator -> hover"/>
			<policy label="layouter -> decorator_margins" report="decorator -> decorator_margins"/>
		</config>
	</start>

	<start name="report_fs">
		<binary name="ram_fs"/>
		<resource name="RAM" quantum="16M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<content>
				<dir name="layouter">
					<inline name="focus"/>
					<inline name="resize_request"/>
					<inline name="rules"/>
					<inline name="window_layout"/>
				</dir>
			</content>
			<policy label="fs_report -> "     root="/" writeable="yes"/>
			<policy label="vfs -> report"     root="/" writeable="yes"/>
			<policy label="report_fs_rom -> " root="/"/>
			<policy label="ro"                root="/"/>
		</config>
	</start>

	<start name="report_fs_rom">
		<binary name="fs_rom"/>
		<resource name="RAM" quantum="3M"/>
		<provides> <service name="ROM"/> </provides>
		<route>
			<service name="File_system"> <child name="report_fs"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="fs_report">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> </provides>
		<config> <vfs> <fs/> </vfs> </config>
		<route>
			<service name="File_system"> <child name="report_fs"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="wm" caps="250">
		<resource name="RAM" quantum="6M"/>
		<provides>
			<service name="Nitpicker"/> <service name="Report"/> <service name="ROM"/>
		</provides>
		<config>
			<policy label_prefix="decorator" role="decorator"/>
			<policy label_prefix="layouter"  role="layouter"/>
			<default-policy/>
		</config>
		<route>
			<service name="ROM"    label="resize_request"> <child name="report_rom"/> </service>
			<service name="ROM"    label="focus">          <child name="report_rom"/> </service>
			<service name="ROM"    label_last="clipboard"> <child name="report_rom"/> </service>
			<service name="Report" label_last="shape">     <child name="report_rom"/> </service>
			<service name="Report" label_last="clipboard"> <child name="report_rom"/> </service>
			<service name="Report">                        <child name="report_rom"/> </service>
			<service name="Nitpicker" label=""> <child name="nitpicker" label="wm -> focus"/> </service>
			<any-service> <child name="nitpicker"/> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="layouter">
		<binary name="window_layouter"/>
		<resource name="RAM" quantum="4M"/>
		<route>
			<service name="ROM" label="config"> <child name="config_fs_rom" label="/layouter.config"/> </service>
			<service name="ROM" label="window_list">       <child name="report_rom"/> </service>
			<service name="ROM" label="focus_request">     <child name="report_rom"/> </service>
			<service name="ROM" label="hover">             <child name="report_rom"/> </service>
			<service name="ROM" label="decorator_margins"> <child name="report_rom"/> </service>
			<service name="ROM" label="rules">             <child name="report_fs_rom" label="/layouter/rules"/> </service>
			<service name="Report" label="rules">          <child name="fs_report"/>  </service>
			<service name="Report">                        <child name="report_rom"/>  </service>
			<service name="Nitpicker"> <child name="wm"/> </service>

			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="decorator" caps="350">
		<binary name="init"/>
		<resource name="RAM" quantum="12M"/>
		<route>
			<service name="ROM" label="config">
				<child name="config_fs_rom" label="/decorator_init.config"/> </service>

			<service name="ROM"    label="window_layout">     <child name="report_rom"/> </service>
			<service name="ROM"    label="pointer">           <child name="report_rom"/> </service>
			<service name="Report" label="decorator_margins"> <child name="report_rom"/> </service>
			<service name="Report" label="hover">             <child name="report_rom"/> </service>
			<service name="Nitpicker"> <child name="wm"/> </service>

			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="launchpad" priority="-1" caps="1000">
		<resource name="RAM" quantum="20M"/>
		<config>
			<launcher name="nit_fb" ram_quota="7M" caps="100">
				<config initial_width="500" initial_height="400" />
			</launcher>
			<launcher name="nitpicker" ram_quota="1M" caps="100">
				<config>
					<domain name="default" layer="2" content="client"
					        label="no" hover="always" focus="click"/>
					<default-policy domain="default"/>
				</config>
			</launcher>
			<launcher name="testnit" ram_quota="1M" caps="100"/>
		</config>
		<route>
			<any-service> <child name="wm"/> <parent/> <any-child/>
			</any-service>
		</route>
	</start>

	<start name="backdrop" priority="-1">
		<resource name="RAM" quantum="24M"/>
		<config>
			<libc/>
			<vfs>
				<rom name="genode_logo.png"/>
				<rom name="grid.png"/>
			</vfs>
			<fill color="#224433" />
			<image png="grid.png"        tiled="yes" alpha="200" />
			<image png="genode_logo.png" anchor="bottom_right" alpha="150"
			                             xpos="-20" ypos="-20" />
		</config>
		<route>
			<any-service> <child name="nitpicker" label="backdrop"/> <parent/> <any-child/>
			</any-service>
		</route>
	</start>

	<start name="nit_fb">
		<resource name="RAM" quantum="6M"/>
		<provides>
			<service name="Input"/>
			<service name="Framebuffer"/>
		</provides>
		<route>
			<service name="Nitpicker">
				<child name="wm"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
		<config xpos="0" ypos="0" width="800" height="600"/>
	</start>

	<start name="wm_backdrop" priority="-1">
		<binary name="backdrop" />
		<resource name="RAM" quantum="24M"/>
		<config>
			<libc/>
			<vfs>
				<rom name="genode_logo.png"/>
			</vfs>
			<fill color="#664455" />
			<image png="genode_logo.png" scale="zoom" alpha="150" />
			<image png="genode_logo.png" scale="fit" alpha="150" tiled="yes" />
			<image png="genode_logo.png" />
		</config>
		<route>
			<any-service> <child name="wm"/> <parent/> <any-child/>
			</any-service>
		</route>
	</start>

	<start name="terminal" caps="110">
		<resource name="RAM" quantum="2M"/>
		<provides><service name="Terminal"/></provides>
		<route>
			<service name="ROM" label="config"> <parent label="terminal.config"/> </service>
			<service name="Framebuffer">
				<child name="nit_fb"/> </service>
			<service name="Input">
				<child name="nit_fb"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="vfs" caps="120">
		<resource name="RAM" quantum="30M"/>
		<provides><service name="File_system"/></provides>
		<config>
			<vfs>
				<tar name="coreutils.tar" />
				<tar name="vim.tar" />
				<tar name="bash.tar" />

				<dir name="home"> <ram/> </dir>
				<dir name="share"> <dir name="vim"> <rom name="vimrc"/> </dir> </dir>
				<dir name="tmp"> <ram/> </dir>
				<dir name="dev">
					<zero/> <null/> <terminal/>
					<dir name="pipe"> <pipe/> </dir>
					<inline name="rtc">2018-01-01 00:01</inline>
				</dir>
				<dir name="config"> <fs label="config"/> </dir>
				<dir name="report"> <fs label="report"/> </dir>
			</vfs>

			<policy label_prefix="vfs_rom" root="/"/>
			<default-policy root="/" writeable="yes"/>
		</config>
		<route>
			<service name="File_system" label="config"> <child name="config_fs"/> </service>
			<service name="File_system" label="report"> <child name="report_fs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="vfs_rom">
		<resource name="RAM" quantum="30M"/>
		<binary name="fs_rom"/>
		<provides> <service name="ROM"/> </provides>
		<config/>
		<route>
			<service name="File_system"> <child name="vfs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="/bin/bash" caps="1000">
		<resource name="RAM" quantum="30M" />
		<config ld_verbose="yes">
			<libc stdin="/dev/terminal" stdout="/dev/terminal"
			      stderr="/dev/terminal" rtc="/dev/rtc" pipe="/dev/pipe"/>
			<vfs> <fs/> </vfs>
			<arg value="bash"/>
			<env key="TERM" value="screen"/>
			<env key="PATH" value="/bin" />
		</config>
		<route>
			<service name="File_system"> <child name="vfs"/> </service>
			<service name="ROM" label_suffix=".lib.so"> <parent/> </service>
			<service name="ROM" label_last="/bin/bash"> <child name="vfs_rom"/> </service>
			<service name="ROM" label_prefix="/bin"> <child name="vfs_rom"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>
</config>}

#
# Pin the nitpicker focus to the window manager by providing a static focus ROM
#
set fd [open [run_dir]/genode/focus w]
puts $fd "<focus label=\"wm -> focus\"/>"
close $fd

file copy -force [genode_dir]/repos/gems/recipes/raw/motif_wm/wm.config [run_dir]/genode/
file copy -force [genode_dir]/repos/gems/recipes/raw/motif_wm/layouter.config [run_dir]/genode/

build { lib/ld test/fork test/execve server/fs_rom server/fs_report
        app/window_layouter app/decorator server/nitpicker server/wm test/nitpicker }

build_boot_image { window_layouter decorator nitpicker wm testnit fs_report
                   ld.lib.so libc.lib.so libm.lib.so vfs.lib.so posix.lib.so fs_rom }

run_genode_until forever
